---
name: Auto Merge Pre-Commit CI PRs

"on":
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.actor == 'pre-commit-ci[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_FORKS: "false"
